#!/usr/bin/env python3

def main():
    
    #name input var
    name = input("What is your name?:")
    #day input var
    day = input("What day is it?:")

    #print statment
    print("Hello, ", name,"! ", "Happy ", day,"!", sep="")

main()
